batch-size = 32
config-path = config.toml
data-path = data_split_300.csv
output-dir = train_classification_10
ensemble-size = 5
task-type = classification
metrics = [binary-mcc, roc, prc, accuracy, f1]
show-individual-scores = true
epochs = 32
num-folds = 10
splits-column = split
num-workers = 0
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
message-hidden-dim = 300
depth = 3
dropout = 0.2
activation = RELU
aggregation = norm
aggregation-norm = 100
ffn-hidden-dim = 300
ffn-num-layers = 2
v-kl = 0.0
eps = 1e-08
warmup-epochs = 2
init-lr = 0.00001
max-lr = 0.0001
final-lr = 0.00001
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
data-seed = 0
multiclass-num-classes = 3
